#!/bin/bash

NEXT_USER="<<NEXT_USER>>"
FLAG="<<FLAG>>"

# Test for nginx presence

if [ -e /etc/nginx/nginx.conf ]; then
    echo "[+] Nginx has been installed"
else
    echo "[-] Nginx not installed"
    echo "[?] How do we install packages?"
    exit 1
fi

# Try website
res=`curl http://localhost:8080`

HTML=$(cat <<-EOF
<html>
    <head>
        <title>You did it!</title>
    </head>
    <body>
        <h1>Congrats! Your website is live!</h1>
    </body>
</html>
EOF
)

if [ "HTML" = $res ]; then
    echo "[+] HTML output matches!"
    echo "[+] Congrats! Here's a flag: $FLAG"
fi
